<?php

namespace App\Support\ProjectIndex;

/**
 * Catálogo conceptual de Entre Sabores. Mantenido a mano; no inventar features.
 * El índice decide qué leer. El código es la fuente de verdad.
 */
final class Catalog
{
    public const SCHEMA_VERSION = 1;

    public const TRUTH_RULE = 'El índice decide QUÉ LEER, no QUÉ ES VERDAD. El código es la fuente de verdad.';

    /**
     * @return array{
     *     project: array{id: string, name: string, summary: string},
     *     scan_roots: list<string>,
     *     ignore: list<string>,
     *     nodes: list<array<string, mixed>>
     * }
     */
    public static function definition(): array
    {
        return [
            'project' => [
                'id' => 'entre-sabores',
                'name' => 'Entre Sabores',
                'summary' => 'Red social gastronómica: muro, publicaciones con etiquetas, likes, comentarios, perfiles y análisis de maridaje por IA.',
            ],
            'scan_roots' => [
                'app',
                'bootstrap',
                'config',
                'routes',
                'resources/views',
                'resources/js',
                'resources/css',
                'tests',
                'database',
                'lang',
                'docker',
                '.cursor',
                '.githooks',
                'docker-compose.yml',
                'Dockerfile',
                'composer.json',
                'package.json',
                'vite.config.js',
                'tailwind.config.js',
                'phpunit.xml',
                'README.md',
                'DOCUMENTACION.md',
                'ARCHITECTURE.md',
                'BACKEND.md',
                'FRONTEND.md',
                'DATABASE.md',
                'SECURITY.md',
                'PRODUCTION.md',
                'PERFORMANCE.md',
                'DOCKER.md',
                'CHANGELOG.md',
                '.env.example',
            ],
            'ignore' => [
                'vendor',
                'node_modules',
                'storage',
                'public/build',
                'public/hot',
                'public/storage',
                '.project/fingerprints.json',
                '.project/metadata.json',
                '.project/overview.json',
                '.project/index.json',
                '.project/graph.json',
                '.project/filemap.json',
            ],
            'nodes' => self::nodes(),
        ];
    }

    public static function hash(): string
    {
        $encoded = json_encode(self::definition(), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

        return sha1(is_string($encoded) ? $encoded : '');
    }

    /**
     * @return list<array<string, mixed>>
     */
    private static function nodes(): array
    {
        return [
            self::n(
                'entre-sabores',
                'project',
                'Entre Sabores',
                null,
                'Raíz conceptual del monolito Laravel 13 de la red social gastronómica.',
                [],
                ['README.md', 'ARCHITECTURE.md', 'bootstrap/app.php'],
                ['entre sabores'],
            ),

            self::n('domain.social', 'domain', 'Red social', 'entre-sabores', 'Muro, publicaciones, likes, comentarios, seguimiento y etiquetas.', ['routes/web.php'], ['app/Http/Controllers/WallController.php'], ['feed', 'social']),
            self::n('domain.identity', 'domain', 'Identidad', 'entre-sabores', 'Auth Breeze, perfiles públicos y ajustes de cuenta.', ['routes/auth.php'], ['app/Models/User.php'], ['cuenta', 'usuario']),
            self::n('domain.ai', 'domain', 'IA', 'entre-sabores', 'Guardia de contenido, job de moderación y análisis de maridaje.', ['app/Jobs/AnalyzePostJob.php', 'app/Jobs/GeneratePostAnalysisJob.php'], ['app/Services/MaridajeAiAnalysisService.php'], ['openai', 'analisis']),
            self::n('domain.realtime', 'domain', 'Tiempo real', 'entre-sabores', 'Reverb/Echo: canales privados y broadcasts de likes, comentarios, notificaciones y IA.', ['app/Providers/BroadcastServiceProvider.php'], ['routes/channels.php'], ['websocket', 'echo']),
            self::n('domain.notifications', 'domain', 'Notificaciones', 'entre-sabores', 'Bandeja in-app, payload JSON, observer de conteo y prune.', ['app/Http/Controllers/NotificationController.php'], ['app/Support/NotificationApiPayload.php'], ['inbox', 'campana']),
            self::n('domain.platform', 'domain', 'Plataforma', 'entre-sabores', 'Marketing, UI Blade/JS, cabeceras de seguridad y observabilidad.', ['resources/views/layouts/'], ['resources/js/app.js'], ['ux', 'csp']),
            self::n('domain.infrastructure', 'domain', 'Infraestructura', 'entre-sabores', 'Kernel Laravel, datos, Docker y el índice de proyecto.', ['bootstrap/', 'app/Providers/'], ['bootstrap/app.php'], ['kernel', 'docker']),
            self::n('domain.docs', 'domain', 'Documentación', 'entre-sabores', 'Markdown técnico del repo; no sustituye el código.', ['DOCUMENTACION.md'], ['ARCHITECTURE.md'], ['docs']),
            self::n('domain.tests', 'domain', 'Pruebas', 'entre-sabores', 'PHPUnit Feature/Unit; señal real de comportamiento.', ['tests/'], ['phpunit.xml'], ['phpunit']),

            self::n(
                'social.wall',
                'feature',
                'Muro / feed',
                'domain.social',
                'Dashboard y JSON del feed: FYP vs siguiendo, sort recent/popular/trending.',
                [
                    'app/Http/Controllers/WallController.php',
                    'app/Http/Requests/FilterPostsRequest.php',
                    'resources/views/wall/',
                    'resources/js/wall.js',
                    'config/performance.php',
                    'PERFORMANCE.md',
                ],
                [
                    'app/Http/Controllers/WallController.php',
                    'app/Services/WallFeedService.php',
                    'app/Http/Requests/FilterPostsRequest.php',
                    'resources/js/wall.js',
                    'ARCHITECTURE.md',
                ],
                ['muro', 'fyp', 'siguiendo', 'feed', 'para ti', 'recientes', 'populares', 'tendencia'],
                ['social.wall.feed', 'social.posts', 'social.tags'],
            ),
            self::n(
                'social.wall.feed',
                'service',
                'WallFeedService',
                'social.wall',
                'Único lugar que decide qué posts salen y en qué orden (mix 70/30, ranking, caché invitado).',
                ['app/Services/WallFeedService.php'],
                ['app/Services/WallFeedService.php'],
                ['wallfeed', '70/30', 'engagement'],
                ['social.posts'],
            ),
            self::n(
                'social.posts',
                'feature',
                'Publicaciones',
                'domain.social',
                'Alta, edición, detalle, policy e imagen; encola maridaje y aplica ContentGuard al crear.',
                [
                    'app/Http/Controllers/PostController.php',
                    'app/Http/Requests/StorePostRequest.php',
                    'app/Http/Requests/UpdatePostRequest.php',
                    'app/Http/Resources/PostResource.php',
                    'app/Policies/PostPolicy.php',
                    'app/Models/Post.php',
                    'resources/views/posts/',
                    'resources/js/post-show.js',
                    'resources/js/social/postCard.js',
                    'database/factories/PostFactory.php',
                    'database/seeders/PostSeeder.php',
                    'database/migrations/2026_04_28_000002_create_posts_table.php',
                    'database/migrations/2026_04_28_100002_refactor_posts_for_tags_and_comment_threads.php',
                    'database/migrations/2026_05_05_100000_add_ai_analysis_to_posts_table.php',
                    'database/migrations/2026_05_05_120000_add_analysis_lifecycle_fields_to_posts_table.php',
                    'database/migrations/2026_05_05_130000_add_moderation_status_fields_to_posts_table.php',
                    'tests/Feature/PostStoreTest.php',
                    'tests/Feature/PostUpdateTest.php',
                ],
                [
                    'app/Http/Controllers/PostController.php',
                    'app/Models/Post.php',
                    'app/Policies/PostPolicy.php',
                    'app/Http/Resources/PostResource.php',
                    'app/Http/Requests/StorePostRequest.php',
                ],
                ['post', 'publicacion', 'reanalyze', 'comida', 'bebida'],
                ['social.tags', 'ai.moderation', 'ai.maridaje'],
            ),
            self::n(
                'social.likes',
                'feature',
                'Likes',
                'domain.social',
                'Toggle de like, modelo Like, evento PostLiked y notificación al autor.',
                [
                    'app/Http/Controllers/PostLikeController.php',
                    'app/Models/Like.php',
                    'app/Events/PostLiked.php',
                    'app/Notifications/NewLikeNotification.php',
                    'database/migrations/2026_04_28_110000_create_likes_table.php',
                    'tests/Feature/ProfileLikedPostsTest.php',
                    'tests/Feature/WallSocialFeaturesTest.php',
                ],
                [
                    'app/Http/Controllers/PostLikeController.php',
                    'app/Models/Like.php',
                    'app/Events/PostLiked.php',
                ],
                ['me gusta', 'like', 'toggle'],
                ['social.posts', 'notifications.inbox', 'realtime.broadcasting'],
            ),
            self::n(
                'social.comments',
                'feature',
                'Comentarios',
                'domain.social',
                'Hilos de comentarios, resource JSON, evento CommentCreated y notificación.',
                [
                    'app/Http/Controllers/PostCommentController.php',
                    'app/Http/Requests/StorePostCommentRequest.php',
                    'app/Http/Resources/CommentResource.php',
                    'app/Models/Comment.php',
                    'app/Events/CommentCreated.php',
                    'app/Notifications/NewCommentNotification.php',
                    'resources/js/social/commentThread.js',
                    'database/migrations/2026_04_28_000003_create_comments_table.php',
                    'tests/Feature/WallSocialFeaturesTest.php',
                ],
                [
                    'app/Http/Controllers/PostCommentController.php',
                    'app/Models/Comment.php',
                    'app/Http/Resources/CommentResource.php',
                    'resources/js/social/commentThread.js',
                ],
                ['comentario', 'hilo', 'thread', 'respuesta'],
                ['social.posts', 'notifications.inbox', 'realtime.broadcasting'],
            ),
            self::n(
                'social.follows',
                'feature',
                'Seguimiento',
                'domain.social',
                'Seguir/dejar de seguir por username y notificación de nuevo seguidor.',
                [
                    'app/Http/Controllers/FollowController.php',
                    'app/Notifications/NewFollowerNotification.php',
                    'database/migrations/2026_04_28_000004_create_follows_table.php',
                    'tests/Feature/WallSocialFeaturesTest.php',
                ],
                [
                    'app/Http/Controllers/FollowController.php',
                    'app/Notifications/NewFollowerNotification.php',
                ],
                ['seguir', 'follower', 'following', 'seguido'],
                ['identity.auth', 'notifications.inbox'],
            ),
            self::n(
                'social.tags',
                'feature',
                'Etiquetas y países',
                'domain.social',
                'Catálogo de tags (caché), búsqueda, ISO de país y banderas en el post.',
                [
                    'app/Http/Controllers/TagController.php',
                    'app/Models/Tag.php',
                    'app/Models/Country.php',
                    'app/Support/CountryNameIsoMap.php',
                    'database/migrations/2026_04_28_000001_create_countries_table.php',
                    'database/migrations/2026_04_28_100000_create_tags_table.php',
                    'database/migrations/2026_04_28_100001_create_post_tag_table.php',
                    'database/migrations/2026_04_30_100000_add_name_index_to_tags_table.php',
                    'database/migrations/2026_04_30_140000_add_iso_code_to_tags_table.php',
                    'database/migrations/2026_04_30_140001_add_iso_code_to_countries_drop_flag_emoji.php',
                    'database/seeders/TagSeeder.php',
                    'database/seeders/GastronomyTagsCatalog.php',
                    'database/seeders/CountrySeeder.php',
                    'database/factories/CountryFactory.php',
                    'tests/Feature/TagSearchTest.php',
                ],
                [
                    'app/Http/Controllers/TagController.php',
                    'app/Models/Tag.php',
                    'app/Support/CountryNameIsoMap.php',
                ],
                ['tag', 'etiqueta', 'pais', 'iso', 'bandera', 'catalogo'],
                [],
            ),

            self::n(
                'identity.auth',
                'feature',
                'Autenticación',
                'domain.identity',
                'Login, registro, reset, verificación de email y modelo User (Breeze).',
                [
                    'app/Http/Controllers/Auth/',
                    'app/Http/Requests/Auth/',
                    'app/Models/User.php',
                    'resources/views/auth/',
                    'routes/auth.php',
                    'lang/es/auth.php',
                    'lang/es/passwords.php',
                    'database/factories/UserFactory.php',
                    'database/migrations/0001_01_01_000000_create_users_table.php',
                    'tests/Feature/Auth/',
                ],
                [
                    'app/Http/Controllers/Auth/AuthenticatedSessionController.php',
                    'app/Http/Controllers/Auth/RegisteredUserController.php',
                    'app/Models/User.php',
                    'routes/auth.php',
                ],
                ['login', 'registro', 'password', 'breeze', 'sesion'],
                [],
            ),
            self::n(
                'identity.profile',
                'feature',
                'Perfil y cuenta',
                'domain.identity',
                'Perfil público, posts del usuario, likes del perfil y settings de cuenta.',
                [
                    'app/Http/Controllers/ProfileController.php',
                    'app/Http/Controllers/UserController.php',
                    'app/Http/Controllers/UsernameAvailabilityController.php',
                    'app/Http/Requests/ProfileUpdateRequest.php',
                    'app/Http/Requests/UserPostsRequest.php',
                    'resources/views/profile/',
                    'resources/views/settings/',
                    'resources/js/profilePosts.js',
                    'resources/js/profileLikes.js',
                    'resources/js/ui/profilePage.js',
                    'resources/js/ui/profileShareModal.js',
                    'resources/js/ui/usernameAvailability.js',
                    'tests/Feature/ProfileTest.php',
                    'tests/Feature/UsernameAvailabilityTest.php',
                    'tests/Feature/ProfileLikedPostsTest.php',
                ],
                [
                    'app/Http/Controllers/ProfileController.php',
                    'app/Http/Controllers/UserController.php',
                    'resources/views/profile/show.blade.php',
                    'app/Http/Controllers/UsernameAvailabilityController.php',
                ],
                ['perfil', 'username', 'settings', 'cuenta', 'ajustes'],
                ['identity.auth', 'identity.photos', 'social.posts'],
            ),
            self::n(
                'identity.photos',
                'service',
                'Foto de perfil',
                'identity.profile',
                'Recorte, WebP y comando de migración de avatares (Intervention Image).',
                [
                    'app/Services/ProfilePhotoService.php',
                    'app/View/Components/AvatarCropper.php',
                    'app/Console/Commands/MigrateProfilePhotosToWebpCommand.php',
                    'resources/views/components/avatar-cropper.blade.php',
                    'resources/js/ui/avatarCropper.js',
                    'config/profile_photo.php',
                    'config/image.php',
                ],
                [
                    'app/Services/ProfilePhotoService.php',
                    'app/View/Components/AvatarCropper.php',
                ],
                ['avatar', 'webp', 'cropper', 'foto'],
                [],
            ),

            self::n(
                'ai.moderation',
                'feature',
                'Moderación de contenido',
                'domain.ai',
                'ContentGuard en el alta, AnalyzePostJob + AIService y rechazo con notificación.',
                [
                    'app/Services/ContentGuard.php',
                    'app/Jobs/AnalyzePostJob.php',
                    'app/Notifications/PostRejectedNotification.php',
                    'app/Events/Broadcasting/PostModerationUpdatedBroadcast.php',
                ],
                [
                    'app/Services/ContentGuard.php',
                    'app/Jobs/AnalyzePostJob.php',
                    'app/Services/AIService.php',
                ],
                ['moderacion', 'flagged', 'rejected', 'content guard', 'profanity'],
                ['ai.moderation.engine', 'social.posts', 'realtime.broadcasting'],
            ),
            self::n(
                'ai.moderation.engine',
                'service',
                'AIService de moderación',
                'ai.moderation',
                'Llama a la API de moderación (config services.content_moderation_ai) y devuelve flagged/reasons.',
                ['app/Services/AIService.php'],
                ['app/Services/AIService.php'],
                ['content_moderation_ai', 'flagged'],
                ['ai.moderation'],
            ),
            self::n(
                'ai.maridaje',
                'feature',
                'Análisis de maridaje',
                'domain.ai',
                'Job de maridaje, reanalyze del dueño, broadcast al terminar y UI de volteo.',
                [
                    'app/Jobs/GeneratePostAnalysisJob.php',
                    'app/Events/Broadcasting/PostAnalysisGeneratedBroadcast.php',
                    'resources/js/social/maridajeFlip.js',
                    'tests/Feature/PostReanalyzeTest.php',
                ],
                [
                    'app/Services/MaridajeAiAnalysisService.php',
                    'app/Jobs/GeneratePostAnalysisJob.php',
                    'app/Http/Controllers/PostController.php',
                    'resources/js/social/maridajeFlip.js',
                ],
                ['maridaje', 'pairing', 'score', 'afinidad', 'reanalyze', 'historia'],
                ['ai.maridaje.engine', 'social.posts', 'realtime.broadcasting'],
            ),
            self::n(
                'ai.maridaje.engine',
                'service',
                'MaridajeAiAnalysisService',
                'ai.maridaje',
                'Invoca MARIDAJE_AI_API_KEY y normaliza historia/afinidad/equilibrio/recomendacion/score.',
                ['app/Services/MaridajeAiAnalysisService.php'],
                ['app/Services/MaridajeAiAnalysisService.php'],
                ['maridaje_ai', 'score'],
                ['ai.maridaje'],
            ),

            self::n(
                'realtime.broadcasting',
                'feature',
                'Broadcasting',
                'domain.realtime',
                'Canales user.{id}, listeners Echo y payloads de eventos sociales e IA.',
                [
                    'app/Providers/BroadcastServiceProvider.php',
                    'app/Events/Broadcasting/',
                    'app/Listeners/Broadcasting/',
                    'routes/channels.php',
                    'resources/js/echo.js',
                    'config/broadcasting.php',
                    'config/reverb.php',
                    'tests/Feature/BroadcastingSocialTest.php',
                    'tests/Unit/BroadcastingPayloadTest.php',
                ],
                [
                    'app/Providers/BroadcastServiceProvider.php',
                    'routes/channels.php',
                    'resources/js/echo.js',
                    'app/Listeners/Broadcasting/SendPostLikedBroadcast.php',
                ],
                ['reverb', 'pusher', 'websocket', 'echo', 'broadcast'],
                [],
            ),

            self::n(
                'notifications.inbox',
                'feature',
                'Bandeja de notificaciones',
                'domain.notifications',
                'API de listado/leído, payload estable, observer de unread y comandos prune/sync.',
                [
                    'app/Http/Controllers/NotificationController.php',
                    'app/Support/NotificationApiPayload.php',
                    'app/Observers/DatabaseNotificationObserver.php',
                    'app/Events/NotificationRecorded.php',
                    'app/Console/Commands/PruneNotificationsCommand.php',
                    'app/Console/Commands/SyncUnreadNotificationCountsCommand.php',
                    'resources/js/notificationsNav.js',
                    'resources/views/layouts/partials/nav-notifications.blade.php',
                    'database/migrations/2026_04_29_120000_create_notifications_table.php',
                    'database/migrations/2026_05_02_120000_add_unread_notifications_count_to_users_table.php',
                    'tests/Unit/NotificationApiPayloadTest.php',
                ],
                [
                    'app/Http/Controllers/NotificationController.php',
                    'app/Support/NotificationApiPayload.php',
                    'app/Observers/DatabaseNotificationObserver.php',
                ],
                ['notificacion', 'unread', 'prune', 'campana', 'inbox'],
                ['realtime.broadcasting'],
            ),

            self::n(
                'platform.marketing',
                'feature',
                'Páginas de marketing',
                'domain.platform',
                'Welcome, explorar y cómo funciona (Blade + layout marketing).',
                [
                    'resources/views/welcome.blade.php',
                    'resources/views/explore.blade.php',
                    'resources/views/how-it-works.blade.php',
                    'resources/views/layouts/marketing.blade.php',
                    'resources/views/layouts/partials/marketing-header.blade.php',
                ],
                [
                    'resources/views/welcome.blade.php',
                    'resources/views/how-it-works.blade.php',
                    'resources/views/explore.blade.php',
                    'resources/views/components/seo-head.blade.php',
                    'resources/views/seo/sitemap.blade.php',
                    'app/Http/Controllers/SeoController.php',
                    'config/seo.php',
                    'resources/js/marketing.js',
                    'tests/Feature/SeoTest.php',
                ],
                ['welcome', 'explorar', 'como funciona', 'landing'],
                [],
            ),
            self::n(
                'platform.observability',
                'feature',
                'Salud y métricas',
                'domain.platform',
                '/health, /internal/metrics, crons Vercel, logs JSON y contadores Redis/array.',
                [
                    'app/Http/Controllers/HealthController.php',
                    'app/Http/Controllers/InternalMetricsController.php',
                    'app/Http/Controllers/VercelCronController.php',
                    'app/Http/Middleware/RecordOperationalMetrics.php',
                    'app/Support/OperationalLogger.php',
                    'app/Support/OperationalMetrics.php',
                    'app/Logging/ApplyJsonFormatterTap.php',
                    'config/monitoring.php',
                    'config/logging.php',
                    'tests/Feature/HealthCheckTest.php',
                    'tests/Feature/VercelCronTest.php',
                ],
                [
                    'app/Http/Controllers/HealthController.php',
                    'app/Support/OperationalMetrics.php',
                    'app/Support/OperationalLogger.php',
                    'config/monitoring.php',
                ],
                ['health', 'metrics', 'loki', 'observabilidad'],
                [],
            ),
            self::n(
                'platform.security',
                'feature',
                'Cabeceras y CSP',
                'domain.platform',
                'Middleware SecurityHeaders y config/security.php (CSP, frame, referrer).',
                [
                    'app/Http/Middleware/SecurityHeaders.php',
                    'config/security.php',
                    'SECURITY.md',
                ],
                [
                    'app/Http/Middleware/SecurityHeaders.php',
                    'config/security.php',
                    'SECURITY.md',
                ],
                ['csp', 'headers', 'xss', 'https'],
                [],
            ),
            self::n(
                'platform.ui',
                'feature',
                'UI Blade y JS',
                'domain.platform',
                'Layouts, componentes Blade, módulos ui/ y bundling Vite/Tailwind (sin Alpine).',
                [
                    'app/View/Components/AppLayout.php',
                    'app/View/Components/GuestLayout.php',
                    'resources/views/layouts/app.blade.php',
                    'resources/views/layouts/guest.blade.php',
                    'resources/views/layouts/navigation.blade.php',
                    'resources/views/layouts/settings.blade.php',
                    'resources/views/dashboard.blade.php',
                    'resources/views/components/',
                    'resources/views/errors/',
                    'resources/js/app.js',
                    'resources/js/bootstrap.js',
                    'resources/js/ui/appChromeReset.js',
                    'resources/js/ui/dropdowns.js',
                    'resources/js/ui/flashMessages.js',
                    'resources/js/ui/mobileNav.js',
                    'resources/js/ui/modals.js',
                    'resources/css/app.css',
                    'vite.config.js',
                    'tailwind.config.js',
                    'package.json',
                    'FRONTEND.md',
                ],
                [
                    'resources/js/app.js',
                    'resources/views/layouts/app.blade.php',
                    'resources/views/layouts/navigation.blade.php',
                    'FRONTEND.md',
                ],
                ['blade', 'vite', 'tailwind', 'layout', 'navbar'],
                [],
            ),

            self::n(
                'infra.kernel',
                'configuration',
                'Kernel Laravel',
                'domain.infrastructure',
                'bootstrap, providers, rate limits, rutas web/console y config de runtime.',
                [
                    'bootstrap/',
                    'app/Providers/AppServiceProvider.php',
                    'app/Http/Controllers/Controller.php',
                    'routes/web.php',
                    'routes/console.php',
                    'config/app.php',
                    'config/auth.php',
                    'config/cache.php',
                    'config/database.php',
                    'config/filesystems.php',
                    'config/mail.php',
                    'config/queue.php',
                    'config/session.php',
                    'config/services.php',
                    'composer.json',
                    'artisan',
                    '.env.example',
                    'boost.json',
                ],
                [
                    'bootstrap/app.php',
                    'app/Providers/AppServiceProvider.php',
                    'routes/web.php',
                ],
                ['ratelimit', 'provider', 'middleware', 'env'],
                [],
            ),
            self::n(
                'infra.database',
                'infrastructure',
                'Datos y colas',
                'domain.infrastructure',
                'Migraciones de cache/jobs, índices de rendimiento y DatabaseSeeder.',
                [
                    'database/migrations/0001_01_01_000001_create_cache_table.php',
                    'database/migrations/0001_01_01_000002_create_jobs_table.php',
                    'database/migrations/2026_04_28_170000_add_likes_follows_post_tag_indexes.php',
                    'database/migrations/2026_05_03_100000_add_performance_indexes_posts_notifications.php',
                    'database/seeders/DatabaseSeeder.php',
                    'DATABASE.md',
                ],
                [
                    'DATABASE.md',
                    'database/seeders/DatabaseSeeder.php',
                ],
                ['migracion', 'seeder', 'mysql', 'sqlite'],
                [],
            ),
            self::n(
                'infra.docker',
                'infrastructure',
                'Docker',
                'domain.infrastructure',
                'Compose PHP/Nginx/MySQL/Redis, Supervisor (FPM, Reverb, queue), Dockerfiles y Vercel.',
                [
                    'docker-compose.yml',
                    'Dockerfile',
                    'Dockerfile.vercel',
                    'vercel.json',
                    'docker/',
                    'DOCKER.md',
                    'VERCEL.md',
                    '.env.vercel.example',
                ],
                [
                    'docker-compose.yml',
                    'DOCKER.md',
                    'VERCEL.md',
                    'Dockerfile.vercel',
                    'vercel.json',
                    'docker/php/supervisord-laravel.conf',
                    'docker/vercel/Caddyfile',
                ],
                ['nginx', 'supervisor', 'reverb', 'mysql', 'vercel', 'frankenphp'],
                [],
            ),
            self::n(
                'infra.project-index',
                'infrastructure',
                'Project Intelligence Index',
                'domain.infrastructure',
                'Catálogo conceptual, indexer incremental, CLI artisan y hooks git.',
                [
                    'app/Support/ProjectIndex/',
                    'app/Console/Commands/ProjectIndexCommand.php',
                    'app/Console/Commands/ProjectQueryCommand.php',
                    'tests/Unit/ProjectIndex/',
                    'tests/Feature/ProjectIndex/',
                    '.githooks/',
                    '.cursor/rules/project-intelligence-index.mdc',
                    '.project/README.md',
                ],
                [
                    'app/Support/ProjectIndex/Catalog.php',
                    'app/Support/ProjectIndex/Indexer.php',
                    'app/Support/ProjectIndex/IndexQuery.php',
                    '.project/README.md',
                ],
                ['indice', 'catalog', 'stale', 'relevant'],
                [],
            ),

            self::n(
                'docs.technical',
                'documentation',
                'Documentación técnica',
                'domain.docs',
                'Guías md del repo (arquitectura, backend, frontend, producción).',
                [
                    'README.md',
                    'DOCUMENTACION.md',
                    'ARCHITECTURE.md',
                    'BACKEND.md',
                    'FRONTEND.md',
                    'DATABASE.md',
                    'PRODUCTION.md',
                    'SECURITY.md',
                    'PERFORMANCE.md',
                    'DOCKER.md',
                    'CHANGELOG.md',
                ],
                [
                    'DOCUMENTACION.md',
                    'ARCHITECTURE.md',
                    'README.md',
                ],
                ['documentacion', 'changelog'],
                [],
            ),
            self::n(
                'tests.suite',
                'test',
                'Suite PHPUnit',
                'domain.tests',
                'Feature y Unit; sqlite en memoria según phpunit.xml.',
                ['tests/', 'phpunit.xml'],
                ['phpunit.xml', 'tests/TestCase.php'],
                ['phpunit', 'feature', 'unit'],
                [],
            ),
        ];
    }

    /**
     * @param  list<string>  $paths
     * @param  list<string>  $entrypoints
     * @param  list<string>  $aliases
     * @param  list<string>  $dependsOn
     * @return array<string, mixed>
     */
    private static function n(
        string $id,
        string $type,
        string $name,
        ?string $parent,
        string $summary,
        array $paths,
        array $entrypoints,
        array $aliases = [],
        array $dependsOn = [],
    ): array {
        $node = [
            'id' => $id,
            'type' => $type,
            'name' => $name,
            'parent' => $parent,
            'summary' => $summary,
            'status' => 'implemented',
            'paths' => $paths,
            'entrypoints' => $entrypoints,
            'depends_on' => $dependsOn,
        ];

        if ($aliases !== []) {
            $node['aliases'] = $aliases;
        }

        return $node;
    }
}
